String.toLocaleString({

	"it": {
    "%game-intro"           : "Join the <strong>Superheroes</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-SUPERHEROES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'Cat Woman',
    '%4'                    : 'Green Lantern',
    '%8'                    : 'Green Arrow',
    '%16'                   : 'Shazam',
    '%32'                   : 'Night Wing',
    '%64'                   : 'Fire Storm',
    '%128'                  : 'Aquaman',
    '%256'                  : 'Supergirl',
    '%512'                  : 'Martian Manhunter',
    '%1024'                 : 'The Flash',
    '%2048'                 : 'Wonder Woman',
    '%4096'                 : 'Batman',
    '%8192'                 : 'Superman',
    '%p0'                   : 'Cat Woman',
    '%p4'                   : 'Green Lantern',
    '%p8'                   : 'Green Arrow',
    '%p16'                  : 'Shazam',
    '%p32'                  : 'Night Wing',
    '%p64'                  : 'Fire Storm',
    '%p128'                 : 'Aquaman',
    '%p256'                 : 'Supergirl',
    '%p512'                 : 'Martian Manhunter',
    '%p1024'                : 'The Flash',
    '%p2048'                : 'Wonder Woman',
    '%p4096'                : 'Batman',
    '%p8192'                : 'Superman'

	},

  "en": {
    "%game-intro"           : "Join the <strong>Superheroes</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-SUPERHEROES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'Cat Woman',
    '%4'                    : 'Green Lantern',
    '%8'                    : 'Green Arrow',
    '%16'                   : 'Shazam',
    '%32'                   : 'Night Wing',
    '%64'                   : 'Fire Storm',
    '%128'                  : 'Aquaman',
    '%256'                  : 'Supergirl',
    '%512'                  : 'Martian Manhunter',
    '%1024'                 : 'The Flash',
    '%2048'                 : 'Wonder Woman',
    '%4096'                 : 'Batman',
    '%8192'                 : 'Superman',
    '%p0'                   : 'Cat Woman',
    '%p4'                   : 'Green Lantern',
    '%p8'                   : 'Green Arrow',
    '%p16'                  : 'Shazam',
    '%p32'                  : 'Night Wing',
    '%p64'                  : 'Fire Storm',
    '%p128'                 : 'Aquaman',
    '%p256'                 : 'Supergirl',
    '%p512'                 : 'Martian Manhunter',
    '%p1024'                : 'The Flash',
    '%p2048'                : 'Wonder Woman',
    '%p4096'                : 'Batman',
    '%p8192'                : 'Superman'
}

});
